-- explore users
SHOW USERS;

-- my usename is 'LETZDEMO202312'

-- explore existing roles
SHOW ROLES;
SHOW GRANTS TO ROLE USERADMIN;

-- create a role
USE ROLE USERADMIN;
CREATE ROLE DBT_EXECUTOR_ROLE
    COMMENT = 'Role for the users running DBT models';

-- assign privileges to the role
GRANT ROLE DBT_EXECUTOR_ROLE TO USER LETZDEMO202312;


-- grant privileges to the executor role
USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE DBT_EXECUTOR_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_EXECUTOR_ROLE;

-- use role to create a database
USE ROLE DBT_EXECUTOR_ROLE;
CREATE DATABASE DATA_ENG_DBT;

-- optimise warehouse
SHOW WAREHOUSES;
USE ROLE SYSADMIN;
ALTER WAREHOUSE "COMPUTE_WH" SET
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Default Warehouse';


-- create dbt user
USE ROLE USERADMIN;
CREATE USER IF NOT EXISTS DBT_EXECUTOR
    COMMENT = 'User running DBT commands'
    PASSWORD = 'password123'
    DEFAULT_ROLE = DBT_EXECUTOR_ROLE
    DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE DBT_EXECUTOR_ROLE TO USER DBT_EXECUTOR;
USE ROLE DBT_EXECUTOR_ROLE;

-- hotfix commands
-- USE ROLE ACCOUNTADMIN;
-- GRANT ALL PRIVILEGES ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;